[package]
name = "mcsled"
version = "0.1.0"
authors = ["leiliang22 <leiliang835@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
